language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - pip install docker-compose
  - docker-compose -f develop.yml up -d
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - docker ps -a
  - sleep 10 && python ./manage.py init_install
script:
  - coverage run --include="$PWD/*" manage.py test account
  - coverage report