dist: trusty
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
  - redis-server
env:
  - POSTGRES_DB=vj_database
  - POSTGRES_USER=vj_username
  - POSTGRES_PASSWORD=vj_password
  - POSTGRES_PORT=5433
before_install:
  - docker version
  - docker run -it -d -e POSTGRES_DB=${POSTGRES_DB} -e POSTGRES_USER=${POSTGRES_USER} -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} -p 127.0.0.1:${POSTGRES_PORT}:5432 postgres:10
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - docker ps -a
  - sleep 10 && python ./manage.py init_install
script:
  - coverage run --include="$PWD/*" manage.py test account
  - coverage report