version: "3"
services:
  vj-postgres-dev:
    image: postgres:10
    container_name: vj-postgres-dev
    restart: always
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vj_database
      - POSTGRES_USER=vj_username
      - POSTGRES_PASSWORD=vj_password
    ports:
      - '127.0.0.1:5432:5432'
